Comment and clean the stata wrappers

diff --git a/scripts/stata b/scripts/stata
--- a/scripts/stata
+++ b/scripts/stata
@@ -1,12 +1,24 @@
 #!/bin/sh
-# a wrapper for Stata to make it more behave like a Unix interpreter:
+# Wrap Stata so that scripts (do-files) behave like a Unix interpreter:
 # - the only argument is a .do file to run
 # - the output is sent to stdout
 #  - But because of how Stata is hard-coded you won't see output until the entire script is finished
+# - exit codes are bubbled up to the OS (though Stata exit codes are 16 bit at least and C exit codes are only 8)
+#
+# Run like
+# `stata script.do ; echo $?`
+#
+# This has a Windows port in stata.bat, which you should find there. This would almost work on Windows,
+#  but expecting Windows to have bash is a mistake.
 
-# TODO: try to auto-locate Stata based on platform, and pull the corresponding spaghetti code out of test.mk
-# TODO: write Stata.bat so this works on Wandows too
-
+# TODO:
+# [ ] detect if we're pointed at console Stata or GUI Stata.
+#       GUI Stata (which is all you get on OS X and Windows) can only be automated with -e,
+#         which requires running the thing and waiting for it to spit out a logfile that
+#        needs replaying and maybe parsing, but console Stata gives real-time output.
+#        This could be detected by probing with a test program that looks at the c() settings list.
+# [ ] On Windows, read the Stata install location from the registry (`reg query ...`)?
+# [ ] On Windows, handle falling back to stata-32 or the other names it gains, as well
 
 STATA=stata
 if [ "$(uname)" = "Darwin" ]; then
@@ -21,10 +33,6 @@ if ! which "$STATA" >/dev/null 2>/dev/null; then
 fi
 
 SCRIPT="$1"; shift
-
-# TODO: detect if we're pointed at console Stata or GUI Stata
-# GUI Stata (which is all you get on OS X and Windows) can only be automated with -e,
-#  which requires running the thing and waiting for it to spit out a logfile which we then parse
 
 WRAPPER=$(dirname $0)/stata_wrap.do
 
